#include<stdio.h>
#include<string.h>
#include<stdlib.h>
#include<time.h>

/* inputChar
		generates a random character in ascii decimal range [32, 125]
		parameters: N/A
		returns: character c (randomly generated by function)
*/
char inputChar()
{
	char c;
	int val;
    val = (rand() % 94) + 32;		// any ascii character with decimal value in range [32, 125]
    c = val;
    return c;
}

/* inputString
		generates a random string a maximum of 6 characters long, with each
			character being a random character value - options include rstlne and
			1 random vowel (other than 'e') and 3 random consonants (other than
			r, s, t, l, and n) just as in the wheel-of-fortune final puzzle
		parameters: a pointer to a block of memory which can hold up to 6 characters
		returns: a pointer to a block of memory which can hold up to 6 characters
*/
char *inputString(char *inString)
{
	int i, val, vow, cons1, cons2, cons3;
	int strLen = (rand() % 6) + 1;		// randomize length of string
	memset(inString, '\0', 6);		// clear inString

	/* the next code block is just a fun way to pick a random collection of 10 different letters
			based on the wheel-of-fortune final puzzle letters, rstlne + 3 consonants + 1 vowel */
	int vowelOptions[4] = {97, 105, 111, 117};
	val = rand() % 4;
	vow = vowelOptions[val];
	int consonantOptions[16] = {98, 99, 100, 102, 103, 104, 106, 107, 109, 112, 113, 118, 119, 120, 121, 122};
	val = rand() % 16;
	cons1 = consonantOptions[val];
	consonantOptions[val] = consonantOptions[15];
	consonantOptions[15] = -1;
	val = rand() % 15;
	cons2 = consonantOptions[val];
	consonantOptions[val] = consonantOptions[14];
	consonantOptions[14] = -1;
	val = rand() % 14;
	cons3 = consonantOptions[val];
	consonantOptions[val] = consonantOptions[13];
	consonantOptions[13] = -1;

	// fill charOptions array with rstlne + 1 random vowel and 3 random consonants
	int charOptions[10] = {101, 108, 110, 114, 115, 116, vow, cons1, cons2, cons3};
    for (i = 0; i < strLen; i++) {
    	val = (rand() % 11);
    	if (val != 10) { inString[i] = charOptions[val]; } else { inString[i] = '\0'; }
    }
    return inString;
}

void testme()
{
  int tcCount = 0;
  char *s;
  char c;
  int state = 0;
  while (1)
  {
  	s = malloc(sizeof(char) * 6);
    tcCount++;
    c = inputChar();
    s = inputString(s);
    printf("Iteration %d: c = %c, s = %s, state = %d\n", tcCount, c, s, state);

    if (c == '[' && state == 0) state = 1;
    if (c == '(' && state == 1) state = 2;
    if (c == '{' && state == 2) state = 3;
    if (c == ' '&& state == 3) state = 4;
    if (c == 'a' && state == 4) state = 5;
    if (c == 'x' && state == 5) state = 6;
    if (c == '}' && state == 6) state = 7;
    if (c == ')' && state == 7) state = 8;
    if (c == ']' && state == 8) state = 9;
    if (s[0] == 'r' && s[1] == 'e'
       && s[2] == 's' && s[3] == 'e'
       && s[4] == 't' && s[5] == '\0'
       && state == 9)
    {
      printf("error ");
      free(s);
      exit(200);
    }
    free(s);
  }
}


int main(int argc, char *argv[])
{
    srand(time(NULL));
    testme();
    return 0;
}